-------------------
-- BLOCO ANÔNIMO --
-------------------
SET SERVEROUTPUT ON

DECLARE
    X CONSTANT NUMBER := 10;
    Z NUMBER NOT NULL := 20;
BEGIN
    DBMS_OUTPUT.PUT_LINE(X);
    DBMS_OUTPUT.PUT_LINE(Z);
END;